In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [4]:
data = pd.read_csv("C:\\Users\\Kiage Lydiah\\Documents\\DATA SCIENCE\\365Projects\\1.01. Simple linear regression.csv")

In [6]:
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [7]:
y = data.GPA
x = data.SAT

In [9]:
reg_model = LinearRegression()

In [14]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

In [30]:
reg_model.fit(x_matrix,y)

LinearRegression()

In [18]:
reg_model.score(x_matrix, y)

0.40600391479679765

In [19]:
reg_model.intercept_

0.2750402996602803

In [20]:
reg_model.coef_

array([0.00165569])

In [24]:
x_2 = 1740
x_2d = np.array(x_2).reshape(-1,1)
reg_model.predict(x_2d)

array([3.15593751])

In [27]:
new_data = pd.DataFrame(data=['1740', '1760'], columns=['SAT'])
new_data

SAT
0  1740
1  1760

In [28]:
reg_model.predict(new_data)

C:\Users\Kiage Lydiah\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([3.15593751, 3.18905127])

In [32]:
new_data['predict_GPA'] = reg_model.predict(new_data)
new_data

C:\Users\Kiage Lydiah\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


SAT  predict_GPA
0  1740     3.155938
1  1760     3.189051